import Logo from "../../public/assets/images/we-logo.png";
import login from "../../public/assets/images/login.png";

export const WeLogo = Logo;
export const loginvector = login;

import heroV from "../../public/assets/videos/hero-video.mp4";
import branding from "../../public/assets/videos/branding.gif";
import experiences from "../../public/assets/videos/experiences.gif";
import products from "../../public/assets/videos/products.gif";
import medvarsity from "../../public/assets/images/medavarsity.png";
import farmfood from "../../public/assets/images/farmfood.png";
import odc from "../../public/assets/images/odc.png";
import krishna from "../../public/assets/images/krishna.png";
import band from "../../public/assets/images/band.png";
import logo_1 from "../../public/assets/images/logos/logo_1.png";
import logo_2 from "../../public/assets/images/logos/logo_2.png";
import logo_3 from "../../public/assets/images/logos/logo_3.png";
import logo_4 from "../../public/assets/images/logos/logo_4.png";
import logo_5 from "../../public/assets/images/logos/logo_5.png";
import logo_6 from "../../public/assets/images/logos/logo_6.png";
import logo_7 from "../../public/assets/images/logos/logo_7.png";
import logo_8 from "../../public/assets/images/logos/logo_8.png";

export const HeroVideo = heroV;
export const brandingV = branding;
export const experiencesV = experiences;
export const productsV = products;
export const medvarsityV = medvarsity;
export const farmfoodV = farmfood;
export const odcV = odc;
export const krishnaV = krishna;
export const bandV = band;
export const logo_1V = logo_1;
export const logo_2V = logo_2;
export const logo_3V = logo_3;
export const logo_4V = logo_4;
export const logo_5V = logo_5;
export const logo_6V = logo_6;
export const logo_7V = logo_7;
export const logo_8V = logo_8;
